### ISSUE TITLE
.github/workflos/docker-push.yml pode receber variável

### ISSUE THREAD

**Issue by huogerac** [walison17/django-fly-deploy#8]
Hey @walison17 , você deve saber, mas dá para fazer uma pequena alteração do YML e deixar mais "genérico" entre projetos...

Ficou legal seu repo [👏](https://emojipedia.org/clapping-hands/)

No lugar de 
```
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghrc.io/walison17/django-fly
```

Podemos utilizar uma variável 
```
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghrc.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}
```
